import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// import Layout from '../components/Layout';
// import CommonLayout from "@/components/CommonLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        {children}
        {/* <CommonLayout>{children}</CommonLayout> */}
      </body>
    </html>
  );
}
